name: Call Parent In service 1
run-name:  ${{ github.actor }} Initiated the Run.
on: 
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run the workflow against'
        type: environment
        required: true
  pull_request:
    branches: [ main ]
    paths: 'service1/**'

jobs:
  build-and-test:
    uses: rajasagarr/SERVICE_1/.github/workflows/parent.yml@latest
    with:
      data: 'data passed from ci flow'
